### ISSUE TITLE
[Bug] Media playback just doesnt work somtimes (doesnt happen on firefox)

### ISSUE THREAD

**Issue by 32bitx64bit** [Floorp-Projects/Floorp#571] opened 2023-11-14 21:36 UTC
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Just watching videos will randomly fail, no matter what I do, the only fix is to restart. Which is 1: really f*(king annoying. 2: Ruins my workflow.

This bug does **not** happen on firefox.

I have reset profiles multiple times, with and without extensions, I've tried multiple things in about:config without any success.
Even removed floorp entirely and reinstalled it.

### To Reproduce

Watch any video(s), wait for awhile and just watch videos on either YouTube, Twitch, Odysee, THE HUB? Raelly just anything that has video playback.

### Expected behavior

Supposed to render out the video like Firefox, normally just playback.

### OS Info

windows 10 *debloated*

### Floorp Version

0.15.1

### Additional context

Video playback works perfectly fine on any other browser, such as Firefox, librewolf, CHROME EVEN. Every single browser but floorp doesnt work.

I also have sidebar2 extensions enabled.

**Comment by 32bitx64bit** [comment] 2023-11-15 02:04
Just to add on to this, using Intel Iris graphics WITH driver installed.

**Comment by 32bitx64bit** [comment] 2023-11-15 06:56
Also was **NOT** able to reporduce on Floorp Lighting

**Comment by surapunoyousei** [comment] 2023-11-15 13:20
In fact, the Lightning version shares source code with the regular version.  I've seen similar reports in Firefox, and the fix is ​​unclear.

**Comment by 32bitx64bit** [comment] 2023-11-15 17:29
> In fact, the Lightning version shares source code with the regular version. I've seen similar reports in Firefox, and the fix is ​​unclear.

Lol idk, might be the way floorp handles media playback.

**Comment by 32bitx64bit** [comment] 2023-11-15 20:39
Small update, it appears to be a h.264 issue.
Which can be recreated on Floorp, and Floorp lighting. Though I cant see to reproduce on Firefox

**Comment by surapunoyousei** [comment] 2023-11-16 00:34
Hmm, I will check build config

**Comment by 32bitx64bit** [comment] 2023-11-18 04:14
Any news? Still a issue.

**Comment by surapunoyousei** [comment] 2023-11-18 04:17
I have investigated and the problem does not exist. Try initializing the profile. It would be fair to suspect a problem in your environment when there are no other reports.

**Comment by gunir** [comment] 2023-11-18 07:55
> Any news? Still a issue.

Create a new profile and test again:
- `about:profiles`
- Create a new profile
If problem is gone, then you need to find it yourself because you've probably created this issue.

**Comment by 32bitx64bit** [comment] 2023-11-19 05:57
> > Any news? Still a issue.
> 
> Create a new profile and test again:
> 
>     * `about:profiles`
> 
>     * Create a new profile
>       If problem is gone, then you need to find it yourself because you've probably created this issue.

I've already done this multiple times.
I have completely wiped floorp off my system, deleted all the profiles, deleted everything. and yet its still a issue.

**Comment by gunir** [comment] 2023-11-20 02:42
> > > Any news? Still a issue.
> > 
> > 
> > Create a new profile and test again:
> > ```
> > * `about:profiles`
> > 
> > * Create a new profile
> >   If problem is gone, then you need to find it yourself because you've probably created this issue.
> > ```
> 
> I've already done this multiple times. I have completely wiped floorp off my system, deleted all the profiles, deleted everything. and yet its still a issue.

For Youtube, Google is throttling non-Chrome: https://old.reddit.com/r/firefox/comments/17ywbjj/whenever_i_open_a_youtube_video_in_a_new_tab_its/

**Comment by 32bitx64bit** [comment] 2023-11-20 04:05
This most commonly happens when you're watching a video / stream on one website, and move onto another website, for example Twitch -> YouTube

**Comment by surapunoyousei** [comment] 2023-11-20 04:07
I can't reproduce it, so I'll close it.

**Closed** 2023-11-20 04:06 UTC
Labels: bug

**Comment by 32bitx64bit** [comment] 2023-11-20 04:07
Can't replicate on firefox, only happens on floorp, maybe its because this uses ESR releases.

**Comment by surapunoyousei** [comment] 2023-11-20 04:09
Google often adds code that causes problems with non-Chromium browsers; Firefox may just not be affected by this as it has recently gotten faster.

**Comment by 32bitx64bit** [comment] 2023-11-20 04:12
> Google often adds code that causes problems with non-Chromium browsers; Firefox may just not be affected by this as it has recently gotten faster.

Maybe, it seems that using Canvasblocker and making it use a "Google" use agent stops the problem from happening.
So it might just have been YouTube purposefully breaking firefox for zero reason, other than "You should chrome, and be happy."

**Comment by creeper-0910** [comment] 2023-11-20 05:02
We have tested this issue in multiple environments and have not been able to reproduce the issue, so we are closing this issue.
