### ISSUE TITLE
[Bug]: The touchpad doesn't let me enlarging text the pages, but in firefox it works

### ISSUE THREAD

**Issue by GustavoJCL** [Floorp-Projects/Floorp#1064] opened 2024-04-02 03:44 UTC
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When i try to use 2 finger in the touch pad for enlarging the text in floorp it doesn't work, but in firefox it work perfectly fine

### Reproduction Steps

1. Install floorp
2. use 2 finger in the touchap to try to enlarge the text

### Expected Behavior

this is the expected behavior in Firefox
![image](https://github.com/Floorp-Projects/Floorp/assets/93671143/c0407218-c1d3-4e22-a6e3-f58a51acaf60)

### Actual Behavior

this is actual behavior of floorp
![image](https://github.com/Floorp-Projects/Floorp/assets/93671143/3e3ddab1-e29b-4ab5-ab03-76fd0853274d)

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/93671143/c0407218-c1d3-4e22-a6e3-f58a51acaf60)
![image](https://github.com/Floorp-Projects/Floorp/assets/93671143/3e3ddab1-e29b-4ab5-ab03-76fd0853274d)

### Browser Version

11.11.2

### Operating System

Arch Linux

**Comment by TheChilledBuffalo** [comment] 2024-04-02 07:22
This should be fixed by Floorp 12, when the next ESR version of Firefox gets released.

And this is a duplicate of #786

**Closed** 2024-04-04 00:33 UTC
Labels: bug, P5, unconfirmed
