### ISSUE TITLE
[Bug]  Vertical Tabs illegible with white text on light background.

### ISSUE THREAD

**Issue by TungstenIodide** [Floorp-Projects/Floorp#371] opened 2023-08-12 11:45 UTC
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Vertical Tab Bar is illegible with white text on light background 

### To Reproduce

Floorp 11.1.0 Flatpak on Fedora Kinoite.

Theme Mode set to Dark
Firefox theme set to system/auto.

The issue is fixed by changing the Theme Mode to light or changing the Firefox theme to either dark or light.

### Expected behavior

Dark 'Theme Mode' should fully change the theme of the vertical tabs like it does when setting to light one.

### Screenshots

System theme with dark theme mode (the only combination where the bug exists)
![image](https://github.com/Floorp-Projects/Floorp/assets/134203940/d0633d85-9933-40e7-bb44-65cd6811d4e0)

System theme with light theme mode
![image](https://github.com/Floorp-Projects/Floorp/assets/134203940/bfa685fb-1207-481d-ab52-0c0fc93d66b4)

Dark theme with dark theme mode
![image](https://github.com/Floorp-Projects/Floorp/assets/134203940/e7051840-e50c-4eb0-ac9f-435238d91ce9)

Light theme with dark theme mode
![image](https://github.com/Floorp-Projects/Floorp/assets/134203940/4ebf1b55-b165-4d93-8b8b-87de14e33e09)

### OS Info

Fedora Kinoite (flatpak)

### Floorp Version

11.1.0

**Comment by surapunoyousei** [comment] 2023-08-12 11:47
It seems caused by GTK...

We cannot fix it because, it affect by OS.

**Comment by surapunoyousei** [comment] 2023-08-12 11:48
Change theme is completely fixed it. We cannot do about that...

**Comment by TungstenIodide** [comment] 2023-08-12 11:49
No problem. At least a workaround exists and if somebody searches for it, they might find it.


I was wondering why setting the theme mode to light changes the theme correctly, not causing an opposite issue, and thought it might be therefore fixable somehow.

**Comment by surapunoyousei** [comment] 2023-08-12 11:51
Thank you for submitting an issue.

 I can't fix this, so I'm closing it as wontfix

**Closed by surapunoyousei** 2023-08-12 11:51 UTC
Labels: bug
