### ISSUE TITLE
[Bug]: Floorp always uses XWayland, even when forced

### ISSUE THREAD

**Issue by Vistaus** [Floorp-Projects/Floorp#980] opened 2024-03-04 12:36 UTC
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Floorp uses XWayland by default. Even when I specifically enable Wayland, either in /etc/environment or in the launcher item, it still uses XWayland.

### Reproduction Steps

-Enable Wayland;
-Notice it still uses XWayland.

### Expected Behavior

It should utilize Wayland.

### Actual Behavior

It utilizes XWayland instead.

### Screenshots

-

### Browser Version

11.10.5

### Operating System

openSUSE Tumbleweed with KDE 5.27

**Comment by TheChilledBuffalo** [comment] 2024-03-05 10:33
Do you use GNOME?

**Comment by Vistaus** [comment] 2024-03-05 10:34
Sorry, forgot to mention: I use KDE.

**Comment by TheChilledBuffalo** [comment] 2024-03-05 10:35
Hmm... that's weird, have you tried it with Firefox ESR? not regular Firefox

**Comment by Vistaus** [comment] 2024-03-05 10:37
I have not. But that shouldn't really make a difference since Floorp is based on ESR and utilizes the same switches/parameters to start it in Wayland mode.

**Comment by TheChilledBuffalo** [comment] 2024-03-05 10:38
Floorp doesn't change any code related to the window protocol. So its most probably an issue with Firefox.

If the issue occurs with Firefox ESR, but not regular Firefox, then it should get fixed with the next ESR release. That should be Floorp 12.

**Comment by Vistaus** [comment] 2024-03-05 10:39
Okay, thanks. I'll wait for Floorp 12 then.

**Comment by TheChilledBuffalo** [comment] 2024-03-05 10:41
Would be great if you could cross-check with Firefox ESR. Just to make sure. And you may also close this issue.

**Comment by Vistaus** [comment] 2024-03-05 10:44
Maybe I'll check later, when I have more time. I'll close this issue as soon as this is no longer an issue, most like with the release of Floorp 12.

**Comment by surapunoyousei** [comment] 2024-03-07 02:27
If you are not able to reproduce it in Firefox ESR, please do not submit this issue in the first place.

We will only address Floorp-specific issues. In the meantime, we will keep this issue closed.

**Closed by surapunoyousei** 2024-03-07 02:27 UTC
Labels: bug, P5, unconfirmed

**Comment by Dusky-dev** [comment] 2024-03-10 13:13
Found a workaround.

Edit the app shortcut and add to the Enviroment Variables "MOZ_ENABLE_WAYLAND=1 GTK_USE_PORTAL=0"
Also set "widget.use-xdg-desktop-portal.file-picker" to 1 in about:config.

You only need "MOZ_ENABLE_WAYLAND=1" but the others are for fixing the cursor.

**Comment by Vistaus** [comment] 2024-03-10 13:48
Thanks, I had already tried that, but that didn't work for me. Just tried it again and nope.

**Comment by johcastn** [comment] 2024-03-19 15:23
> Thanks, I had already tried that, but that didn't work for me. Just tried it again and nope.

Maybe this can help. I have installed Floorp via flatpak. I have disabled the option to show windows with X11 in the Flatpak Permission page on the System Settings. That has worked for me. My system also runs with Tumbleweed and KDE 6.
