### ISSUE TITLE
[Bug]  Hides search bar on full screen.

### ISSUE THREAD

**Issue by sapatevaibhav** [Floorp-Projects/Floorp#609] opened 2023-12-02 11:59 UTC
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When I am in full [F11] screen and I want to do something in a new tab it must activate the search bar after opening the new tab.

### To Reproduce

1. Press F11 or simply go to full screen
2. Enter ```ctrl + t```  to open new tab

### Expected behavior

After opening the new tab search must be triggered by temporarily showing search bar after pressing enter it must hide again.

### OS Info

Linux Mint 21.2 Cinnamon 

### Floorp Version

11.6.1

**Comment by creeper-0910** [comment] 2023-12-02 12:48
Is it a bug?
Or is it a feature request?

**Comment by surapunoyousei** [comment] 2023-12-02 14:12
I can't reproduce it and I don't think it is that big of a problem, so I will close it.

My apologize

**Closed** 2023-12-02 14:12 UTC
Labels: bug
