### ISSUE TITLE
[Bug]: KeepassXC Browser Extension does not stay connected

### ISSUE THREAD

**Issue by sga11** [Floorp-Projects/Floorp#1038] opened 2024-03-25 20:24 UTC
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

(First of all, i understand it is not solely related to floop and revolves around keepassxc more, but i used to use librewolf prior where this issue was not present, so i am guessing floorp is somehow involved, i apologize in advance if this issue is not relevant to floorp)(also when i mention librewolf, i do not mean to compare projects, i practically mean the latest stable firefox of time, but i only tried in librewolf)(also i apologize for any issues due to spellings/grammar(i am not a native speaker))
Whenever keepassxc/floorp is restarted (for example on system restart), it does not connect with browser extension (pressing the reload button does not work) (as i understand, they make a connection, which stays established during the session)

### Reproduction Steps

Install keepassxc browser extension, keepassxc, and create a database with browser integration enabled
1. restart either of the 2
2. try to reconnect by pressing
I have attached my attempt at enabling browser integration, i also have tried to tick to firefox checkbox, but that is also not persistent (posting the screenshot with the check box not ticked to show the issue)
![2024-03-04_10-23](https://github.com/Floorp-Projects/Floorp/assets/154851398/20bf5523-f61f-415d-9ac7-619724631d57)
![2024-03-04_10-23_1](https://github.com/Floorp-Projects/Floorp/assets/154851398/0a6bc9b5-70c9-458f-b31d-f2e9d2da6e97)
I did not even add the custom location when i used to use librewolf

### Expected Behavior

Either it should auto-connect (best case scenario, but i think that did not even work in librewolf)
or it should connect when pressing the reconnect button

### Actual Behavior

posted alongside relevant section
it does not reconnect on pressing the button, i have to open keepass xc, go to settings, re-tick the check box, then press the reconnect and then re-detect fields, and then it works (i understand this is not hard enough, but slightly cumbersome, as i have a very long password
![2024-03-04_10-19](https://github.com/Floorp-Projects/Floorp/assets/154851398/7ae63642-7810-416c-85e0-987072f7efac)
)

### Screenshots

posted alongside relevant section

### Browser Version

Mozilla floorp 11.11.2 (From Chaotic-AUR)(experienced in prior versions(11.10.3-current) also)

### Operating System

Linux Black 6.8.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000 x86_64 GNU/Linux (Endeavour OS)

**Comment by TheChilledBuffalo** [comment] 2024-03-26 06:24
Could you please check if this occurs with Firefox ESR? If it does, then you might have to submit an issue there.

**Comment by sga11** [comment] 2024-03-26 12:00
i could not reproduce in firefox-esr, but now that i have tried to reproduce in floorp, i could not exactly reproduce it every time (only 2 out of 5 times), should i close this issue ?

**Comment by surapunoyousei** [comment] 2024-03-27 05:56
It is presumed to be a Linux-specific problem.

This issue is closed as it is often caused by Floorp not being supported.

**Closed by surapunoyousei** 2024-03-27 05:56 UTC
Labels: bug, P5, unconfirmed

**Comment by CuteistFox** [comment] 2024-05-11 01:52
Can reproduce
