### ISSUE TITLE
[Bug] No tab drag / detach animation.

### ISSUE THREAD

**Issue by RDELX** [Floorp-Projects/Floorp#261] opened 2023-05-16 17:30 UTC
### Describe the bug

When I try to drag a horizontal tab it doesn't show me a drag animation as Firefox does.

### To Reproduce

1. Have at least 2 tabs open in horizontal mode
2. Grab a tab with left click
3. Move your tab over the other tab

### Expected behavior

It should preview the position of tab will be when the left click is released.

### Screenshots

Floorp:

![Screenshot 2023-05-16 202625](https://github.com/Floorp-Projects/Floorp/assets/51673029/066501c7-3e12-438c-871b-0b850ffc6309)

Firefox:

![Screenshot 2023-05-16 202540](https://github.com/Floorp-Projects/Floorp/assets/51673029/386a310d-1790-4e3e-a11f-19ef5026a685)

### OS Info

Windows 11 22H2 Enterprise

### Floorp Version

10.13.0

**Comment by surapunoyousei** [comment] 2023-05-18 00:48
If you change the design to Proton UI, will this issue be resolved?

**Comment by RDELX** [comment] 2023-05-18 13:33
Alright so it is the **multi-row tabs** that causes this problem. Animation got fixed after disabling it.

**Comment by surapunoyousei** [comment] 2023-05-18 13:38
Unfortunately this is by design. Animation is disabled due to the effect of tab replacement when using multiple tabs.

I'm sorry, but I will close the issue

**Closed by surapunoyousei** 2023-05-18 13:38 UTC
Labels: bug

**Comment by Versette** [comment] 2025-02-06 14:26
Very annoying issue. I would like to always use this option, but having no animation makes it pretty unusable for me...
