### ISSUE TITLE
New revolutionary ideas to enhanche browsing 

### ISSUE THREAD

**Issue by trimechee** [Floorp-Projects/Floorp#173] opened 2023-01-12 11:38 UTC
Hello @surapunoyousei , after months of hard search, i think these tricks and modifcation can make Floorp browser even most faster and speed and battery saver, it will be great to add option to enable or disable them with one click , thank you !

browser.sessionstore.privacy_level 2

accessibility.force_disabled	1

 browser.tabs.firefox-view false

browser.sessionstore.idleDelay 1

browser.sessionstore.interval.idle 2147483647

browser.sessionstore.interval 2147483647

DISABLE SESSION STORAGE

browser.sessionstore.max_tabs_undo 0

browser.sessionstore.max_windows_undo 0

browser.sessionstore.resume_from_crash FALSE

Browser.startup.page 0

browser.cache.disk.content_type_media_limit

MemoryReduction

Reduce session history entries

user_pref("browser.sessionhistory.max_entries", 0);

Turn off bfcache

user_pref("browser.sessionhistory.max_total_viewers", 0);

full-screen-api.warning.timeout 0
full-screen-api.transition-duration.enter = "0 0"
full-screen-api.transition-duration.leave = "0 0"
browser.fullscreen.autohide

browser.sessionhistory.max_entries	5
	
browser.sessionhistory.max_total_viewers	5

****CACHE

https://kanasys.com/tech/892
https://wiki.calculate-linux.org/firefox

about:cache

browser.cache.disk.max_entry_size 128 (disable youtube cache)

browser.cache.disk.parent_directory (changer dossier cache)

browser.cache.disk.enable = false
browser.cache.memory.enable = false
browser.cache.offline.enable = false

set 

browser.cache.disk.smart_size.enabled 

REDEMARRAGE

browser.cache.disk.enable

browser.cache.disk_cache_ssl 
and
 browser.cache.offline.enable to false

browser.cache.offline.capacity 0

browser.cache.disk.capacity 0

    activate the entry browser.cache.memory.enable -> true

    set the entry browser.cache.memory.capacity to -1 for automatic adjustment

Browser.cache.memory.capacity  0

 browser.cache.disk.capacity 0

browser.cache.disk.content_type_media_limit

media.cache_size 2147483647

browser.privatebrowsing.forceMediaMemoryCache true 

browser.cache.disk.enable - false
browser.cache.disk.smart_size.enabled - false
browser.cache.disk_cache_ssl - false
browser.cache.offline.enable - false

browser.cache.memory.enable - true (I believe this is true by default)
browser.cache.memory.capacity - 512000 (that's 500 MB, I actually have mine set to 1 GB)

browser.cache.disk.capacity = 8192000 # 8 GB cache on disk
browser.cache.disk.smart_size.enabled = false # disable adaptive cache size on disk
browser.cache.frecency_half_life_hours = 128 # lower cache sweep intervals
browser.cache.max_shutdown_io_lag = 16 # let the browser finish more io on shutdown
browser.cache.memory.capacity = 2097152 # fixed maximum 2 GB in memory cache
browser.cache.memory.max_entry_size = 327680 # maximum size of in memory cached objects

https://gist.github.com/RubenKelevra/fd66c2f856d703260ecdf0379c4f59db

browser.cache.disk.content_type_media_limit

 A percentage limit for media content type in the disk cache. When some entries
+# need to be evicted and media is over the limit, it's evicted first.
+- name: browser.cache.disk.content_type_media_limit
https://hg.mozilla.org/releases/mozilla-release/rev/bbc2d5705a2b0647ea2c6aabd86b7a79df836b81

- browser.cache.disk.enable = false
(désactive le cache disk)
- browser.cache.disk.capacity = 0
(interdit le cache disk)
- browser.cache.memory.enable = true
(active le cache de la ram, accélère Mozilla)
- browser.cache.memory.capacity ou browser.cache.memory.max_entry_size = 20000 (Ram pour le cache)
- browser.cache.offline.enable = false
(Désactive le cache offline)
- browser.cache.offline.capacity = 0
(interdit le cache offline)
- network.http.sendRefererHeader = 0
(n'informe pas le site de vos ancien site visité)
- network.prefetch-next = false
(Ne stock rien dans le cache)

 browser.cache.disk.max
    browser.cache.disk.max_entry_size = 51200 // 50 MB 

turn off [browser.cache.disk.smart_size.enabled] and [browser.cache.disk.enable],

If you increase [browser.cache.memory.max_entry_size] to 1048576

I set browser.cache.disk.capacity = 0 and my Win10 Firefox is much faster

browser.privatebrowsing.forceMediaMemoryCache set to true (and it works)

*** Buffer full video or make buffer bigger

https://hg.mozilla.org/mozilla-central/rev/b597ea8f9bb4

So what actually changed is that these values changed from:

Buffer full video or make buffer bigger

There is an easy fix for it just increase media.cache_readhead_limit 
to 9999 and media.cache_resume_treshold also to 9999. 
This was also puzzling me since firefox 54 would buffer 
till the end of the video but firefox 55 wouldn't, 
so I went trough the about:config and found those
 two lines once I chagned their values from (60, 30)
 to those above every single video I opened in firefox so far buffered till the end, you don't even need to restart the firefox just refresh the page for changes to take the effect. Hope this helped.

cache_readahead_limit: 999999  9999
cache_resume_threshold: 999999  9999

to

cache_readahead_limit: 60
cache_resume_threshold: 30

media.cache_readahead_limit
media.cache_readahead_limit.cellular

media.cache_resume_threshold
media.cache_resume_threshold.cellular

Increase the size of 

browser.cache.disk.content_type_media_limit

media.cache_size 2147483647

Increase 

browser.cache.disk.capacity

You can set media.mediasource.enabled to false. 
If a site's video playback breaks, try to revert this option back
 to the default, before anything else.
Set media.mediasource.enabled to false so it works on Youtube

media.preload.default

media.volume_scale

media.throttle-regardless-of-download-rate

media.throttle-factor

media.throttle-regardless-of-download-rate false

media.video-queue.default-size

media.wakelock_timeout

prevent video elements from preloading too much data
 pref("media.preload.default", 1); // default to preload none
 pref("media.preload.auto", 2);    // preload metadata if preload=auto
 pref("media.cache_size", 32768);    // 32MB media cache

**Comment by typeling1578** [comment] 2023-01-12 12:33
duplicate of #131

**Closed by typeling1578** 2023-01-12 12:33 UTC
Labels: enhancement

**Comment by trimechee** [comment] 2023-01-12 16:47
@typeling1578 this not duplicate https://github.com/Floorp-Projects/Floorp/issues/131 , i said "new ideas" in the title, there is new options and setting and this is summary of  the best of of the best of  hard secret search , i hope you will reopen this thread to help enhance Floorp, I wrote this for our beloved developer @surapunoyousei

**Comment by creeper-0910** [comment] 2023-01-12 16:55
Please post to the issue you previously put up.
