### ISSUE TITLE
[Bug] Clicking the profile picture in the toolbar creates 3 popups saying "No apps available"

### ISSUE THREAD

**Issue by AlexPewMaster** [Floorp-Projects/Floorp#756] opened 2024-01-21 15:58 UTC
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Whenever I click my own profile picture in the toolbar of Floorp, I get 3 popups saying "No apps available".

![image](https://github.com/Floorp-Projects/Floorp/assets/68469103/e91fdebd-ab1d-4b1e-bf5e-ce9e8e1eb665)
_(Blurred for privacy reasons)_

### To Reproduce

1. Open the Floorp Flatpak
2. Click on your profile picture of your Firefox account 
![image](https://github.com/Floorp-Projects/Floorp/assets/68469103/28e2d37c-c7ef-449b-92b2-022c6a73ffa4)
3. Get 3 popups saying "No apps available"

### Expected behavior

The sync menu should open normally.

### OS Info

Fedora Workstation 39 (DE: GNOME 45.3)

### Floorp Version

Flatpak 11.8.1 (64-bit)

### Additional context

This could be related to my bookmarks, as I have "Modrinth" saved on my bookmarks toolbar. I'm not quite sure though.

**Comment by surapunoyousei** [comment] 2024-01-21 16:00
Frankly, I am dubious that this is a Floorp issue. Looking at your post it feels like a request sent for an extension and is unlikely to be related to your Firefox account.

**Comment by surapunoyousei** [comment] 2024-01-21 16:01
If you not get issue on new profile, I will close this issue.

Please create new profile & Turn on Sync with your Mozilla Account

**Comment by AlexPewMaster** [comment] 2024-01-21 16:08
I created a new test user profile and it behaved normally, until my extensions got synced. Once Floorp started to sync my extensions, the bug came back. This issue might be related to my extensions, should I post a list of my installed extensions here?

**Comment by AlexPewMaster** [comment] 2024-01-21 16:11
This issue is also occurring on my Steam Deck. I'm also using the same Floorp Flatpak version there.

**Comment by surapunoyousei** [comment] 2024-01-21 16:15
If it occurs after synchronization, then the extension is the cause.

**Comment by surapunoyousei** [comment] 2024-01-21 16:16
So. If you can use "apt", Use PPA instead of Flatpak. Maybe couses by it.

**Comment by AlexPewMaster** [comment] 2024-01-21 16:17
I use Fedora, so "apt" is not an option. Should I build from source?

**Comment by surapunoyousei** [comment] 2024-01-21 16:18
Tarball.

Download from releases

**Comment by AlexPewMaster** [comment] 2024-01-21 16:31
I'm currently using the tarball release to write this comment; it's working perfectly fine! What caused the Flatpak to behave so weirdly?

**Comment by surapunoyousei** [comment] 2024-01-21 16:32
Flatpak uses a sandbox to run Floorp. It is safe, but causes some problems.

**Closed** 2024-01-22 09:44 UTC
Labels: bug
