### ISSUE TITLE
[Bug]: Sidebar opens a smaller browser interface instead of the desired website

### ISSUE THREAD

**Issue by lunik1** [Floorp-Projects/Floorp#1238] opened 2024-06-22 23:00 UTC
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The sidebar opens a smaller browser interface instead of the desired website

### Reproduction Steps

1. Open a website in the sidebar

### Expected Behavior

The sidebar opens the desired website

### Actual Behavior

See screenshot

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/13547699/faf5c950-fad7-476d-9fae-2c8d30967671)

Fresh profile:

![image](https://github.com/Floorp-Projects/Floorp/assets/13547699/b3d2bf67-e8f1-457d-8cd6-43ca5bd3f8d7)

### Browser Version

11.14.1

### Operating System

NixOS

**Comment by surapunoyousei** [comment] 2024-06-23 03:20
Please present the output of the browser console

**Comment by lunik1** [comment] 2024-06-23 17:05
![image](https://github.com/Floorp-Projects/Floorp/assets/13547699/ab324c94-b715-463a-873f-d89678d05ea1)

**Comment by realskyquest** [comment] 2024-06-23 21:40
The bug is not reproducible on my desktop, the discord app seems bit squashed in there, perhaps a horizontal scrollbar is needed??

It does show a small browser interface, but it flashes then changes into discord

![image](https://github.com/Floorp-Projects/Floorp/assets/135049479/d4433f66-56ec-4ff7-9821-d9afab670fda)

**Browser version**
Floorp 11.14.1 (64-bit)

**Operating system**
Linux mint 21.3 Cinnamon
Cinnamon version 6.0.4
Linux kernal 5.15.0-112-generic 
Display server x11

**Comment by zoovasoup** [comment] 2024-06-24 03:59
i have the same problem, im also on nixos 

Browser version
Floorp 11.14.1 (64-bit)

Operating system
NixOS

![2024-06-24T11:58:18,259105512+08:00](https://github.com/Floorp-Projects/Floorp/assets/55152188/865570ca-145f-44ff-8b54-0ae28dae6512)

**Comment by TheChilledBuffalo** [comment] 2024-06-24 05:03
This issue is specific to NixOS. It should be fixed in the next update.

**Comment by lunik1** [comment] 2024-06-24 08:47
Is there a ticket on nixpkgs?

**Comment by TheChilledBuffalo** [comment] 2024-06-24 09:07
@lunik1 I don't think there is a need for that. This issue arose because the nix package maintainer refused to include "unfree" code. But now, that repository has been archived and will no longer be used. When the next version of Floorp releases, the nix package will compile a fully-featured application. Please wait until then, thanks!

**Comment by lunik1** [comment] 2024-06-24 09:39
Ok, I will try to keep an eye on the nixpkgs tracker and redirect any issues that are opened here. Thanks for the quick and clear response.

**Comment by surapunoyousei** [comment] 2024-06-27 01:53
Floorp has recently enabled extensions to work in the web panel. 

I have implemented this by emulating the browser window inside the web panel to implement this functionality. Because of this, browser toolbar can be see from users small time.

**Comment by realskyquest** [comment] 2024-06-30 19:55
Just want to post this funny thing I discovered.

So yeah I had discord on my sidebar and ofc I set it up properly with the right container, it was working fine but it randomly requires me to re-login?

After I stopped using the sidebar for discord the issue has never occurred. It could be some weird cookie issue ig

**Comment by lunik1** [comment] 2024-07-25 11:36
This issue is fixed for me now,

**Comment by zoovasoup** [comment] 2024-07-25 15:52
yup, updating the flake and rebuilding my system fixed it

**Closed** 2024-07-25 16:35 UTC
Labels: bug, P5, unconfirmed
