### ISSUE TITLE
[Bug] Firefox Side View extension's sidebar cannot be closed nor resized

### ISSUE THREAD

**Issue by win8linux** [Floorp-Projects/Floorp#646] opened 2023-12-24 02:29 UTC
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

When using the [Firefox Side View](https://github.com/mozilla/side-view/) extension from Mozilla, the sidebar it spawns cannot be resized nor closed in any way without disabling it afterwards.

### To Reproduce

Sequence 1:
1. Right-click on page or link
2. Select `Open in sidebar`
3. See sidebar that cannot be closed nor resized

Sequence 2:
1. Click `Open Side View` button in address bar
2. See sidebar that cannot be closed nor resized

Sequence 3:
1. Click Extensions button in main toolbar
2. Open Side View extension
3. Select a website
4. See sidebar that cannot be closed nor resized

### Expected behavior

Side View sidebar opens with a button at the top to close it.

### Screenshots

Firefox:
![Screenshot_20231224_102214](https://github.com/Floorp-Projects/Floorp/assets/11584387/b0685538-a776-4a1d-9316-9507224bbb63)

Floorp:
![Screenshot_20231224_102516](https://github.com/Floorp-Projects/Floorp/assets/11584387/ba009ed4-f7f6-4242-995a-ac4e9b50242e)

### OS Info

Arch Linux

### Floorp Version

11.7.1

### Additional context

A possible alternative to directly fixing this issue is implementing similar transient webpage sidebar functionality in Floorp instead, as proposed in https://github.com/Floorp-Projects/Floorp/discussions/647.

**Comment by surapunoyousei** [comment] 2023-12-24 02:41
Please provide fullscreen screenshot

**Comment by win8linux** [comment] 2023-12-24 04:28
Firefox:
![Screenshot_20231224_122357](https://github.com/Floorp-Projects/Floorp/assets/11584387/ee6aa010-9fa8-4b7e-88a4-734ed6517d9b)

Floorp:

![Screenshot_20231224_122559](https://github.com/Floorp-Projects/Floorp/assets/11584387/72310c8e-84ef-4426-8102-de2d3eeb86ca)

**Comment by surapunoyousei** [comment] 2024-01-01 01:35
Frankly, I cannot reproduce it.

What did you do to your Floorp sidebar or Firefox sidebar before installing the add-on?

**Comment by win8linux** [comment] 2024-01-01 03:30
I didn't really do anything to the Floorp sidebar. In case it's useful though, here are my Tab Bar settings:
![Screenshot_20240101_112858](https://github.com/Floorp-Projects/Floorp/assets/11584387/25fe7b70-3ae5-436f-b654-6ceee9a1feb1)

**Comment by surapunoyousei** [comment] 2024-01-02 15:24
Hmm

**Comment by surapunoyousei** [comment] 2024-01-02 15:26
To be honest, I don't know what is causing this, and CSS doesn't seem to be the problem either.

The inability to resize is most likely a problem with your customization, not with the extension.

I'll close the issue once I have no other reports, but please re-open it once you figure out how to reproduce the issue.

**Closed** 2024-01-02 15:27 UTC
Labels: bug

**Comment by win8linux** [comment] 2024-01-02 15:37
Tracked down the setting causing the issue, it is `Collapse Tree Style Tab`.

`Collapse Tree Style Tab` turned off:
![Screenshot_20240102_233456](https://github.com/Floorp-Projects/Floorp/assets/11584387/e4d0987c-2cff-4c0b-972a-40293a1c0ab9)

`Collapse Tree Style Tab` turned on:
![Screenshot_20240102_233517](https://github.com/Floorp-Projects/Floorp/assets/11584387/39b8152e-eb5a-4a46-8fc1-57e973725991)

**Comment by surapunoyousei** [comment] 2024-01-02 15:37
Ah... yeah. maybe affect to that.
