### ISSUE TITLE
[Bug]: Many media decoders missing

### ISSUE THREAD

**Issue by UltraBlackLinux** [Floorp-Projects/Floorp#1277] opened 2024-07-20 10:28 UTC
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Many media decoders are somehow missing within floorp, but not in firefox.

None of these play in floorp, but they do play in firefox:

https://tools.woolyss.com/html5-audio-video-tester/?u=woolyss.com/f/avc-aac-nerdist-friends.mp4
https://tools.woolyss.com/html5-audio-video-tester/?u=spoonradio.ice.infomaniak.ch/spoonradio-hd.aac
https://tools.woolyss.com/html5-audio-video-tester/?u=woolyss.com/f/audio-sample.m4a

This is more than a minor inconvenience since these are some of the most used media formats :/

### Reproduction Steps

Play a video with one of the codecs above

### Expected Behavior

It plays

### Actual Behavior

It doesn't play

### Screenshots

![image](https://github.com/user-attachments/assets/829c0de9-2c20-4919-9ff0-ed6531d20004)

### Browser Version

11.14.1

### Operating System

Arch Linux

**Comment by regularentropy** [comment] 2024-07-20 10:59
Floorp is based on Firefox ESR 115. Some media decoders are missing in this version.
Please wait for the next update.

**Comment by regularentropy** [comment] 2024-07-20 11:00
Reopened, since it works on Windows.

Check installed codecs on your system.

**Comment by UltraBlackLinux** [comment] 2024-07-20 11:21
I have checked that already. I have ffmpeg installed, which has libavcodec bundled. Other media players work fine, and as I said, firefox works fine too, so it's not a problem on my side

**Comment by regularentropy** [comment] 2024-07-20 11:36
> and as I said, firefox works fine too, so it's not a problem on my side

Have you checked to see if this problem occurs in Firefox ESR 115? If not, please check this.

**Comment by UltraBlackLinux** [comment] 2024-07-20 12:11
what...
it actually doesn't work on ESR

You genuinely need to update your base, that's horrible

**Comment by regularentropy** [comment] 2024-07-20 12:12
Closing issue, since it's not Floorp-related.

**Closed by regularentropy** 2024-07-20 12:12 UTC
Labels: bug, P5, unconfirmed

**Comment by creeper-0910** [comment] 2024-07-20 12:16
Please wait for ESR128.

**Comment by UltraBlackLinux** [comment] 2024-07-20 19:15
has apparently already been released about two weeks ago: https://www.mozilla.org/en-US/firefox/128.0esr/releasenotes/

**Comment by TheChilledBuffalo** [comment] 2024-07-20 19:17
@UltraBlackLinux What he meant, is to wait until that version is adopted by Floorp which should be in the next update.

**Comment by regularentropy** [comment] 2024-08-15 15:47
> When can I expect floorp to update its base? Almost any kind of video is no longer playing, be it simple video files, or even youtube.
> 
> Incredibly frustrating, sadly there aren't any other firefox-based browsers that offer what floorp does...

tomorrow

**Comment by surapunoyousei** [comment] 2024-08-16 18:56
On Linux, the decoder is OS-dependent. Check your operating system.

**Comment by surapunoyousei** [comment] 2024-08-16 18:57
Maybe Flatpak version Floorp helps you

**Comment by UltraBlackLinux** [comment] 2024-08-16 19:06
agh. Annoyingly flatpak works. I'm just not much of a fan of flatpak for various reasons.

I really don't understand why this isn't working, at all.

At this point I'm just gonna switch back to firefox since this is unfortunately quite unbearable.

**Comment by regularentropy** [comment] 2024-08-16 19:17
> I really don't understand why this isn't working, at all.

You have missing codecs on your system. The Flatpak version bundles everything, that's why you don't experience any issues with it.

**Comment by UltraBlackLinux** [comment] 2024-08-16 19:31
it doesn't make any sense. Bare firefox works completely fine, and I already have ffmpeg installed. Arch doesn't even offer a package for just ffmpeg codecs - it must all be bundled into one package...

**Comment by creeper-0910** [comment] 2024-08-16 19:44
If you are using Wayland, this may be the cause.
